name: Build and Package DEB

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl

      - name: Install musl-tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build release binary
        run: |
          cargo build --release --target x86_64-unknown-linux-musl

      - name: Prepare .deb structure
        run: |
          VERSION=$(echo "${GITHUB_REF#refs/tags/v}" || echo "v0.0.1")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          mkdir -p reddy_${VERSION}/DEBIAN
          mkdir -p reddy_${VERSION}/usr/local/bin

          cat <<EOF > reddy_${VERSION}/DEBIAN/control
          Package: reddy
          Version: ${VERSION}
          Section: utils
          Priority: optional
          Architecture: amd64
          Maintainer: Srinivas Reddy Thatiparthy <thatiparthysreenivas@gmail.com>
          Description: Alias manager for shell commands.
          EOF

          cp target/x86_64-unknown-linux-musl/release/reddy reddy_${VERSION}/usr/local/bin/

          cd reddy_${VERSION}/usr/local/bin
          while read -r line; do
            # Get the first word from the line
            cmd=$(echo "$line" | awk '{print $1}')
            [[ -n "$cmd" ]] && ln -s reddy "$cmd"
          done < "$GITHUB_WORKSPACE/src/commands.txt"
          cd -

      - name: Build .deb package
        run: |
          dpkg-deb --build reddy_${{ env.VERSION }}

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: reddy-deb
          path: reddy_*.deb

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: reddy_*.deb

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        run: |
          # Use VERSION from environment
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          # Push the .deb package to GitHub Packages
          curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            -X PUT \
            -H "Content-Type: application/octet-stream" \
            --data-binary @reddy_${{ env.VERSION }}.deb \
            "https://ghcr.io/v2/$OWNER/reddy/blobs/sha256:$(sha256sum reddy_${{ env.VERSION }}.deb | cut -d' ' -f1)"